Calendar implementation
js-tasks-ru/htmlcss-20220919_deniss pull request #11
Opened 2022-10-05 12:41 UTC by Delitl

2022-10-05 12:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-05 17:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-06 08:37 UTC, GSemikozov requested changes

2022-10-06 08:37 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.item_chosen {
.calendar__item_chosen

2022-10-06 08:37 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.item_between {
.calendar__item_between

2022-10-07 01:20 UTC, Delitl commented on 05-lection3/03-calendar/calendar.css
> +.item_chosen {
Поправил

2022-10-07 01:20 UTC, Delitl commented on 05-lection3/03-calendar/calendar.css
> +.item_between {
Поправил

2022-10-07 15:48 UTC, GSemikozov approved these changes

2022-10-07 15:49 UTC, merged