Modal implementation
js-tasks-ru/htmlcss-20220919_deniss pull request #13
Opened 2022-10-06 04:59 UTC by Delitl

2022-10-06 04:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-06 08:38 UTC, GSemikozov requested changes

2022-10-06 08:38 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  --blue-1: #334D6E;
блок растягиваем на весь вьюпорт и позиционируем через fixed + фон задаем через rgba

2022-10-06 08:38 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__background {
и тогда это - лишний элемент

2022-10-07 01:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-07 01:29 UTC, Delitl commented on 05-lection3/02-modal/modal.css
> +  --blue-1: #334D6E;
Поправил

2022-10-07 01:29 UTC, Delitl commented on 05-lection3/02-modal/modal.css
> +.modal__background {
Поправил

2022-10-07 01:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-07 15:48 UTC, GSemikozov approved these changes

2022-10-07 15:49 UTC, merged