Mobile version of main and component pages
js-tasks-ru/htmlcss-20220919_deniss pull request #18
Opened 2022-10-11 22:38 UTC by Delitl

Сделал адаптивными главную страницу и страницу с компонентами. Пока без добавления компонентов. Хочется понять правильно сделал или нет.

2022-10-11 22:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-12 11:31 UTC, GSemikozov requested changes

2022-10-12 11:31 UTC, GSemikozov commented on components/inner-container/inner-container.css
> +    grid-template-columns: 0 1fr;
лучше удалять display: none само меню

2022-10-13 02:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-13 22:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-13 22:38 UTC, Delitl commented
Добавил гистограмму в качестве примера на превью карточку

2022-10-13 22:41 UTC, Delitl commented on components/inner-container/inner-container.css
> +    grid-template-columns: 0 1fr;
Поправил

2022-10-13 23:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-14 15:08 UTC, GSemikozov approved these changes

2022-10-14 15:08 UTC, merged