Theme changer implementation
js-tasks-ru/htmlcss-20220919_deniss pull request #25
Opened 2022-10-19 04:35 UTC by Delitl

2022-10-19 04:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-19 04:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-20 04:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-20 07:47 UTC, GSemikozov requested changes

2022-10-20 07:47 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.icon_light-theme {
toggler__theme-icon_light-theme

2022-10-20 07:47 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.icon_dark-theme {
toggler__theme-icon_dark-theme

2022-10-21 02:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-21 03:04 UTC, Delitl commented on 07-lection5/03-toggler/toggler.css
> +.icon_light-theme {
Поправил

2022-10-21 03:04 UTC, Delitl commented on 07-lection5/03-toggler/toggler.css
> +.icon_dark-theme {
Поправил

2022-10-21 03:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-23 18:06 UTC, GSemikozov approved these changes

2022-10-23 18:06 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-10-23 18:08 UTC, GSemikozov approved these changes

2022-10-23 18:08 UTC, merged