Main page v2 implementation
js-tasks-ru/htmlcss-20220919_deniss pull request #7
Opened 2022-09-29 05:12 UTC by Delitl

2022-09-29 05:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-29 07:49 UTC, GSemikozov requested changes

2022-09-29 07:49 UTC, GSemikozov commented on components/preview/preview.css
> +.preview-cards {
.preview__cards

2022-09-29 07:49 UTC, GSemikozov commented on components/preview/preview.css
> +  justify-content: space-evenly;
если ниже используем gap, то justify-content и align-content не нужны

2022-09-29 16:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-29 16:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-29 16:38 UTC, Delitl commented on components/preview/preview.css
> +.preview-cards {
Поправил

2022-09-29 16:40 UTC, Delitl commented on components/preview/preview.css
> +  justify-content: space-evenly;
Поправил. 
Я эти свойства ставил, чтобы при сжатии экрана карточки более равномерно по экрану разместились. При дефолтном состоянии экрана эти свойства, конечно, не нужны.

2022-09-30 08:23 UTC, GSemikozov approved these changes

2022-09-30 08:23 UTC, merged